export const CREATE_TASK            = 'CREATE_TASK';
export const RESOLVED_CREATE_TASK   = 'RESOLVED_CREATE_TASK';

export const UPDATE_TASK            = 'UPDATE_TASK';
export const RESOLVED_UPDATE_TASK   = 'RESOLVED_UPDATE_TASK';

export const DELETE_TASK            = 'DELETE_TASK';
export const RESOLVED_DELETE_TASK   = 'RESOLVED_DELETE_TASK';

export const ADD_TASK_FROM_SOCKETS  = 'ADD_TASK_FROM_SOCKETS';

export const SORT_TASKS_LIST        = 'SORT_TASKS_LIST';
export const RESOLVED_SORT_TASKS_LIST = 'RESOLVED_SORT_TASKS_LIST';
